# Generated by Django 4.2.10 on 2024-04-01 06:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase", "0007_alter_purchaserequisition_quantity_requested_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=255)),
                ("invoice_date", models.DateField(auto_now_add=True)),
                ("account_number", models.CharField(max_length=255)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("payment_due_date", models.DateField()),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("pending", "Pending")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_report_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_id", models.CharField(max_length=255)),
                ("receipt_date", models.DateField(auto_now_add=True)),
                (
                    "received_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_inspection", "Pending Inspection"),
                            ("inspected", "Inspected"),
                        ],
                        default="pending_inspection",
                        max_length=20,
                    ),
                ),
                (
                    "received_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                            ("defective", "Defective"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True, null=True)),
                (
                    "inspection_report_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
