# Generated by Django 4.2.10 on 2024-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_inventoryreceipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vendor_rated',
            field=models.BooleanField(default=False),
        ),
    ]
