# Generated by Django 5.0 on 2024-02-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0007_remove_optimizedinventory_annual_demand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_number", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("quantity_requested", models.IntegerField()),
                ("expected_delivery_date", models.DateField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "attachments",
                    models.ImageField(
                        blank=True, null=True, upload_to="requisition/attachments"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True, null=True, upload_to="requisition/reports"
                    ),
                ),
                (
                    "inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_fulfilled", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("days_delivery", models.IntegerField()),
                (
                    "attachments",
                    models.ImageField(blank=True, null=True, upload_to="bid"),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchaserequisition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=255)),
                ("date_ordered", models.DateField(auto_now_add=True)),
                ("quantity_ordered", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.supplierbid",
                    ),
                ),
            ],
        ),
    ]
