# Generated by Django 5.0 on 2024-02-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_gstin"),
        ("purchase", "0002_alter_supplierbid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierbid",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.vendor",
            ),
            preserve_default=False,
        ),
    ]
