# Generated by Django 5.0 on 2024-02-20 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_alter_supplierbid_supplier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplierbid",
            unique_together={("supplier", "requisition")},
        ),
    ]
