# Generated by Django 4.2.10 on 2024-03-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_alter_supplierbid_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity_ordered",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="unit_price",
        ),
    ]
