# Generated by Django 5.0 on 2023-12-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('procurement_officer', 'Procurement Officer'), ('vendor', 'Vendor')], max_length=255),
        ),
    ]
