# Generated by Django 5.0 on 2024-02-19 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_gstin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gstin",
            field=models.CharField(
                default=0,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid GSTIN (Goods and Services Tax Identification Number).",
                        regex="^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}\\d[Z]{1}[A-Z\\d]{1}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
