# Generated by Django 4.2.10 on 2024-03-07 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_gstin"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
