# Generated by Django 4.2.10 on 2024-03-13 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_vendor_address_remove_vendor_vendor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contract_expiry_date',
            field=models.DateField(default=datetime.datetime(2029, 3, 12, 17, 4, 6, 500915)),
        ),
    ]
