# Generated by Django 4.2.10 on 2024-03-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_vendor_contract_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contract_expiry_date',
            field=models.DateField(default=datetime.datetime(2029, 3, 16, 18, 52, 39, 491977)),
        ),
    ]
