# Generated by Django 5.0 on 2024-01-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory'),
        ),
    ]
