# Generated by Django 5.0 on 2024-01-27 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalinventory_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
        migrations.CreateModel(
            name='OptimizedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_demand', models.FloatField()),
                ('ordering_cost', models.FloatField()),
                ('holding_cost', models.FloatField()),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('service_level', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('safety_stock', models.FloatField(blank=True, null=True)),
                ('reorder_point', models.FloatField(blank=True, null=True)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('eoq', models.FloatField(blank=True, null=True)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
