# Generated by Django 5.0 on 2024-01-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventory_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedinventory',
            name='storage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
