# Generated by Django 5.0 on 2024-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_optimizedinventory_storage_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedinventory',
            name='annual_demand',
        ),
        migrations.AddField(
            model_name='optimizedinventory',
            name='demand',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
