# Generated by Django 4.2.10 on 2024-03-17 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_historicalinventory_demand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optimizedinventory",
            name="holding_cost",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
    ]
