name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        id: pylint
        run: pylint --output-format=parseable $(git ls-files '*.py')

      - name: Check Pylint rating
        run: |
          threshold=5.0 
          rating=$(echo "${{ steps.pylint.outputs.pylint }}" | awk -F'[:=]' '/Your module or file name/ {print $6}')
          if (( $(bc <<< "$rating < $threshold") )); then
            echo "Pylint rating is below threshold ($rating). Continue workflow."
          else
            echo "Pylint rating is above threshold ($rating). Marking workflow as successful."
            exit 0
          fi
